<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\EducationManagementSystem.Shared.Dispatcher\EducationManagementSystem.Shared.Dispatcher.csproj" />
    <ProjectReference Include="..\StudentMSystem.AggregateRoot\StudentMSystem.AggregateRoot.csproj" />
    <ProjectReference Include="..\StudentMSystem.DTO\StudentMSystem.DTO.csproj" />
    <ProjectReference Include="..\StudentMSystem.Repository\StudentMSystem.Repository.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Abstractions\" />
  </ItemGroup>

</Project>
