<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CourseMSystem.AggregateRoot\CourseMSystem.AggregateRoot.csproj" />
    <ProjectReference Include="..\CourseMSystem.DTO\CourseMSystem.DTO.csproj" />
    <ProjectReference Include="..\CourseMSystem.Repository\CourseMSystem.Repository.csproj" />
    <ProjectReference Include="..\EducationManagementSystem.Shared.Dispatcher\EducationManagementSystem.Shared.Dispatcher.csproj" />
  </ItemGroup>

</Project>
